defaults:
  - _self_
  - task: walk
  - override hydra/launcher: local
  - override hydra/output: local

hydra:
  job:
    chdir: True

# LLM parameters
model: gpt-5
temperature: 1.0

# Optional checkpoint overrides
# Use relative paths from Isaac Lab root (e.g., logs/rsl_rl/...) or absolute paths
environment_analysis_checkpoint: "logs/rsl_rl/g1_enhanced/2025-08-14_00-40-58/model_700.pt"
evaluation_checkpoint: "logs/rsl_rl/g1_enhanced/2025-08-14_00-40-58/model_700.pt"

task: Forward Locomotion
env_name: isaac_lab_sds_env

train_script: scripts/reinforcement_learning/rsl_rl/train.py
reward_template_file: source/isaaclab_tasks/isaaclab_tasks/manager_based/sds/velocity/mdp/rewards_template.py
reward_output_file: source/isaaclab_tasks/isaaclab_tasks/manager_based/sds/velocity/mdp/rewards.py

# Environment settings - G1 Humanoid Robot (hardcoded)
robot: g1                    # Unitree G1 Humanoid Robot
terrain: flat               # Terrain type: flat, rough
num_envs: 4096              # Number of parallel environments for training
video_length: 500           # Length of video footage and contact analysis in frames

# Environment Analysis Settings
environment_analysis_robots: 50  # Number of robots used for real-time terrain analysis
enable_environment_analysis: true  # Enable/disable environment-aware SUS generation
auto_capture_environment_image: true  # Automatically capture environment image before reward generation

# 🎯 SDS ENVIRONMENT-AWARE MODE CONTROL
# Controls whether reward generation uses environmental information or foundation-only approach
# env_aware: true  = Full environmental sensing + terrain analysis + sensor-based rewards
# env_aware: false = Foundation-only rewards (gait, velocity, posture) with NO environmental info
env_aware: true  # Set to false for foundation-only comparison studies

iteration: 5
sample: 8
train_iterations: 1000
success_keyword: "Training completed successfully"
failure_keyword: Traceback

image_quality: "high"

# Weights and Biases
use_wandb: False # whether to use wandb for logging
wandb_username: "" # wandb username if logging with wandb
wandb_project: "" # wandb project if logging with wandb